spring:
  boot:
     - context: 1.0.0
     - bean: 1.0.0

  cloud:
     - context: 1.2.0
     - bean: 1.2.0
  mvc:
    - context: 1.3.0
    - bean: 1.3.0
  jpa:
    - context: 1.4.0
    - bean: 1.4.0


